language: node_js
node_js:
- '8'
cache: yarn
script:
- yarn --version
- yarn check --integrity
- yarn test

deploy:
  provider: npm
  email: jenkins-reform@HMCTS.NET
  api_key:
    secure: fg24yxrPIpDaLr/Dhkfxtdn1woY46+g3/4tHtkoZHvCkCh9ifviF6Si25gPP8Unz18SxQaoV9dQrHXyzwE6sRyXXVBMz8RMfhAOWUWxnvkKj0FpXGgNi4mpuq85ieIIfb7aw5QlJYT7CFLpox7DYUlXQ/ZkGOu85hROCk0RpFOQQHXsogETWPcLVvRLawDAK2hjAifdIZ9bbFdTnHdn86alCKkBJKVlDlCzks7FNhDe/NHHMLQfWhAciQQZrj7QAfwwxcaQcN7DsxtsY5NiIvyjeDe8vtMBmhJPeDz02wADmwNRZE0iX/AI8MxIhbu9cTyvv28NcmXjIQZNkrbBI61uUzan8QrrbiLVn/rk2o76RwbKIPW5QKRCLtE++1xQ+IkEqPerVKM/hNT3yG/kfE7+/hTOHyeQGhHFn+6G8u9cSaZe5VnUdCl5/DBiB+heN7mahynQFdPqew5bu5Bxl97kQR0i0Avfsx+rrmx6x+F9VK4k2WdVsOMueH1wvy+69EaSLcRnG0q+USwr/2wQbS7fjBqPhELzD5AgpfDE2RswgJtu5nOrCBY94FrM1G4IE8XExzQk072BMgr9r+BUoRcrxQk655FNUhi5FNXuwXh02T4xk+1NQrFOuXJ2znnw0o5+DHi0+gMa59CFJBWJMYWAoQLR4+rg8/kvur5brlic=
  on:
    tags: true
    repo: hmcts/div-service-auth-provider-client
